apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: fastfood 
data:
  POSTGRES_HOST: "users-db-service"
  POSTGRES_DB: "fastfood"
  POSTGRES_PORT: "5432"
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:80"