{{- if not (lookup "v1" "Secret" .Release.Namespace "db-credentials") -}}
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.credentials.user }}"
  POSTGRES_PASSWORD: "{{ .Values.credentials.password }}"
{{- end -}}